include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # We use print for debugging in this prototype
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
